#this is a lookup dictionary to correct spelling errors in data
#where the key is the value in the data
##and the value is what we want to replace it with

correct_spelling = {b'archev\x90que de Toulouse':b'archev\x90que'
                    , b'archev\x90que de Tours':b'archev\x90que'
                    , b'arch\x90veque de Paris':b'archev\x90que'
                    , b'aristocrat in the service of the dauphine':b'aristocrat'
                    , b'aristocrat in the service of the queen':b'aristocrat'
                    , b'army officier':b'army officer'
                    , b'author of handbooks':b'author'
                    , b'businessman':b'business man'
                    , b'captain of a regiment':b'captain'
                    , b'captain of the Swiss guards':b'captain'
                    , b'clergyman':b'clergy'
                    , b'clock-maker':b'clockmaker'
                    , b'courtier?':b'courtier'
                    , b'daughter of M de Courson':b'daughter'
                    , b'daughter of actors':b'daughter'
                    , b'daughter of the Grand-Conti':b'daughter'
                    , b'diplomat and writer of memoirs':b'diplomat'
                    , b'diplomatic official':b'diplomat'
                    , b'ecoomist':b'economist'
                    , b'encyclopaedist':b'encyclopedist'
                    , b'encyclopediste':b'encyclopedist'
                    , b'grammatrian':b'grammarian'
                    , b'laywer':b'lawyer'
                    , b'mar\x8echal de France':b'mar\x8echal'
                    , b'mar\x8echal de camp':b'mar\x8echal'
                    , b'mar\x8echale de France':b'mar\x8echal'
                    , b'minister':b'minster'
                    , b'mistress of Casanova':b'mistress'
                    , b'mistress of Stanislas':b'mistress'
                    , b'officier':b'officer'
                    , b'poet and exegete':b'poet'
                    , b'professor at the Sorbonne':b'professor'
                    , b'pr\x8ecieuse':b'pr\x8eciseuse'
                    , b'receveur g\x8en\x8eral des finances de Soissons':b'receveur g\x8en\x8eral des finances'
                    , b'revolutionary politician':b'revolutionary'
                    , b'wife of Fran\x8dois Bondel':b'wife'
                    , b'wife of a banker':b'wife'
                    , b'wife of a playwright':b'wife'
                    , b'wife of diplomat':b'wife'
                    , b'wife of lieutenant de police':b'wife'
                    , b'wife of mar\x8echal de France':b'wife'
                    , b'wife of the chancelier de France?':b'wife'
                    , b'writer on military matters':b'writer'
                    , b'writer on sport and hunting':b'writer'
                    , b'Aristocracy':b'Aristoracy'
                    , b'Eite':b'Elite'
                    , b'Elite ':b'Elite'
                    , b'Elite?':b'Elite'
                    , b'Government ':b'Government'
                    , b'Government_MP':b'Government'
                    , b'Miltiary':b'Military'

                    }
